---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# openscoring

<!-- badges: start -->
<!-- badges: end -->

A simple package to score creativity data using [OpenScoring](https://openscoring.du.edu/) API. Based on paper by Organisciak, Acar, Dumas and Berthiaume ([2022](http://doi.org/10.13140/RG.2.2.32393.31840)).

## Installation

You can install the development version of openscoring from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jakub-jedrusiak/openscoring")
```

## Example

```{r example}
library(openscoring)

df <- tibble::tibble(
  stimulus = c("brick", "hammer", "sponge"),
  response = c("butter for trolls", "make Thor jeallous", "make it play in a kids show")
)

df

scored_df <- oscai(df, stimulus, response, model = "davinci2")

scored_df
```